// src/components/ui/SectionTitle.tsx
import { RevealOnScroll } from '@/components/animation/RevealOnScroll';
import { cn } from '@/lib/utils/cn';

interface SectionTitleProps {
	title: string;
	subtitle?: string; // The italic colored part
	align?: 'center' | 'left';
}

export function SectionTitle({ title, subtitle, align = 'center' }: SectionTitleProps) {
	return (
		<RevealOnScroll className={cn('mb-16', align === 'center' ? 'text-center' : 'text-left')}>
			<h2 className="text-4xl md:text-5xl font-serif mb-6">
				{title} {subtitle && <span className="italic-accent">{subtitle}</span>}
			</h2>
			<div
				className={cn(
					'w-24 h-1 bg-aura-accent rounded-full opacity-50',
					align === 'center' && 'mx-auto'
				)}
			/>
		</RevealOnScroll>
	);
}

// src/lib/components/SectionTitle.svelte
<script lang="ts">
	interface Props {
		title: string;
		subtitle?: string; // The italic colored part
        align?: 'center' | 'left';
	}

	let { title, subtitle, align = 'center' }: Props = $props();
</script>

<div class="mb-16 animate-fade-up {align === 'center' ? 'text-center' : 'text-left'}">
	<h2 class="text-4xl md:text-5xl font-serif mb-6">
		{title} {#if subtitle}<span class="italic-accent">{subtitle}</span>{/if}
	</h2>
    {#if align === 'center'}
	    <div class="w-24 h-1 bg-aura-accent mx-auto rounded-full opacity-50"></div>
    {:else}
        <div class="w-24 h-1 bg-aura-accent rounded-full opacity-50"></div>
    {/if}
</div>
